name: Build

on: [ push ]

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v3
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Conan
        run: sudo pip install conan
      - name: Cache CMake files
        uses: actions/cache@v3
        with:
          path: |
            build
            ~/.conan
          key: ${{ runner.os }}-run-${{ hashFiles('**/') }}
      - name: Create build dir
        run: mkdir -p build
      - name: Build
        run: |
          cd build
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest --verbose
