name: Memory Sanitizer

on: [ push ]

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Conan
        run: sudo pip install conan
      - name: Create build dir
        run: mkdir build
      - name: Cache CMake files
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-msan-${{ hashFiles('*') }}
          restore-keys: ${{ runner.os }}-msan-
      - name: Load CMake
        run: |
          cd build
          cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITIZER_MEMORY=1
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest
