name: Verify

on: [ push ]

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Conan
        run: sudo pip install conan
      - name: Install cppcheck and clang-tidy
        run: sudo apt-get install cppcheck clang-tidy -y
      - name: Create build dir
        run: mkdir build
      - name: Cache CMake files
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-tidy-${{ hashFiles('*') }}
          restore-keys: ${{ runner.os }}-tidy-
      - name: Build
        run: |
          cd build
          cmake -G Ninja .. -DENABLE_CLANG_TIDY=1 -DENABLE_CPPCHECK=1
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest

# todo: verify formatting
