name: Verify

on: [ push ]

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Install Conan
        run: sudo pip install conan
      - name: Install clang-tidy
        run: sudo apt-get install clang-tidy -y
      - name: Create build dir
        run: mkdir -p build
      - name: Cache CMake files
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-verify-${{ hashFiles('*') }}
          restore-keys: ${{ runner.os }}-verify-
      - name: Build
        run: |
          cd build
          cmake -G Ninja .. -DENABLE_CLANG_TIDY=1
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest --verbose

# todo: verify formatting
